version: '3'

volumes:
  mysql_5_7-data:
  public_data:
  tmp_data:

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_5_7-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    command: bundle exec pumactl start
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - public_data:/mahjong_parlor/public
      - tmp_data:/mahjong_parlor/tmp
    depends_on:
      - db

  web:
    build:
      context: containers/nginx
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    ports:
    - "80:80"
    volumes:
    - public_data:/mahjong_parlor/public
    - tmp_data:/mahjong_parlor/tmp
    depends_on:
      - app
