version: 2.1

jobs:
  rubocop:
    working_directory: ~/mahjong_parlor
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  rspec:
    working_directory: ~/mahjong_parlor
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          - RAILS_ENV: test
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Setup database
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
