default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] || "root" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "" %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>

development:
  <<: *default
  database: mahjong_parlor_development

test:
  <<: *default
  database: mahjong_parlor_test

production:
  <<: *default
  database: mahjong_parlor_production
  username: mahjong_parlor
  password: <%= ENV['MAHJONG_PARLOR_DATABASE_PASSWORD'] %>
